// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sample.Data;

#nullable disable

namespace Sample.Migrations
{
    [DbContext(typeof(TonerContext))]
    [Migration("20211020074536_ThirdCreate")]
    partial class ThirdCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.1.21452.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sample.Models.Printer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("checked_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("floor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("now_record")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tonerid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("tonerid");

                    b.ToTable("printer", (string)null);
                });

            modelBuilder.Entity("Sample.Models.Toner", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("black")
                        .HasColumnType("integer")
                        .HasColumnName("black");

                    b.Property<int>("cyan")
                        .HasColumnType("integer")
                        .HasColumnName("cyan");

                    b.Property<int>("drum")
                        .HasColumnType("integer")
                        .HasColumnName("drum");

                    b.Property<int>("magenta")
                        .HasColumnType("integer")
                        .HasColumnName("magenta");

                    b.Property<int>("recovered_toner")
                        .HasColumnType("integer")
                        .HasColumnName("recovered_toner");

                    b.Property<int>("yellow")
                        .HasColumnType("integer")
                        .HasColumnName("yellow");

                    b.HasKey("id");

                    b.ToTable("toner", (string)null);
                });

            modelBuilder.Entity("Sample.Models.Printer", b =>
                {
                    b.HasOne("Sample.Models.Toner", "toner")
                        .WithMany("Printers")
                        .HasForeignKey("tonerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("toner");
                });

            modelBuilder.Entity("Sample.Models.Toner", b =>
                {
                    b.Navigation("Printers");
                });
#pragma warning restore 612, 618
        }
    }
}
