// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sample.Data;

#nullable disable

namespace Sample.Migrations
{
    [DbContext(typeof(TonerContext))]
    [Migration("20211020065652_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.1.21452.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sample.Models.Toner", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("black")
                        .HasColumnType("integer");

                    b.Property<int>("cyan")
                        .HasColumnType("integer");

                    b.Property<int>("drum")
                        .HasColumnType("integer");

                    b.Property<int>("magenta")
                        .HasColumnType("integer");

                    b.Property<int>("recovered_toner")
                        .HasColumnType("integer");

                    b.Property<int>("yellow")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Toner", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
